### PR TITLE
my first pull request 

### PR DESCRIPTION
**Pull request by dbmohit**
I added ml project and update README accordingly, please review and let me know what you think!

### CODE REVIEW

**Comment by ron2111** [comment]
The project is all good. Could you resolve the spelling errors in the Project Doc & prefer a smaller font size for Project Heading.
FYI, I will merge it after the required changes but contributions before 1st OCT won't be counted as HacktoberFest contributions :)

**Comment by dbmohit** [comment]
thank u for reviewing my pull request, it is my pleasure to follow your mention step. and again Thank you for thinking of me  ·, Thank you for your time today.

**Comment by ron2111** [comment]
Patch is merged,

**Comment by dbmohit** [comment]
Sir is it considered in hacktober fest 2021 pull request?

**Comment by ron2111** [comment]
No, only contributions after 1st Oct would be considered for HacktoberFest 2021.

Don't worry, it's nice that you started early and get familiar with the project.
Also, add your Name & LinkedIn/Github link in the README.md file of the repo under the contributors' section as per the given format.

**Comment by dbmohit** [comment]
Ok sir and please consider that you merge that readme file after 1 oct😅

**Pull request closed without merging**
