### PR TITLE
Weather Forecast

### PR DESCRIPTION
**Pull request by BajraYeJoon**

### CODE REVIEW

**Comment by BajraYeJoon** [comment]
# Weather Forecast Web Application ☁☁

Get real live Weather Data. Search by City and it will show Temperature , State of your current city.

gif

#### Feel free to contribute and star the repo 🌟

## To Contribute 📝

1.fork this repo in your Github.
2.Clone it in your local Machine. ADD features or any other things. 
3. Create branch and create pull request 
4. Wait for review and merge.

Happy Learning. 😄🍸

© Open Source Projects

**Comment by BajraYeJoon** [comment]
# Weather Forecast Web Application ☁☁

Get real live Weather Data. Search by City and it will show Temperature , State of your current city.

gif

#### Feel free to contribute and star the repo 🌟

## To Contribute 📝

1.fork this repo in your Github.
2.Clone it in your local Machine. ADD features or any other things. 
3. Create branch and create pull request 
4. Wait for review and merge.

Happy Learning. 😄🍸

© Open Source Projects

**Comment by ron2111** [comment]
Merging, Star the repo if you like it.

**Comment by BajraYeJoon** [comment]
@ron2111  I have a question. it is hackotberfest-accepted but in hacktoberfest profile. it is showing as matures in 14 days. what does it mean?
I am new to it. Plesae clear my doubt😃

**Pull request merged**
