### PR TITLE
Added Game of Life in React

### PR DESCRIPTION
**Pull request by itsanshulverma**
Issue #1

### CODE REVIEW

**Comment by itsanshulverma** [comment]
Please merge this pr. @Shubhamrawat5 @ramyamahi @PrajjwalDatir

**Comment by Shubhamrawat5** [comment]
Not my repo.

**Comment by itsanshulverma** [comment]
> Not my repo.

okay sorry

**Comment by itsanshulverma** [comment]
Please review and merge this PR! @TechSpiritSS

**Pull request merged**
