### PR TITLE
Added Photo Site

### PR DESCRIPTION
**Pull request by ManasviGoyal**

### CODE REVIEW

**Comment by ManasviGoyal** [comment]
@ron2111 please check

**Comment by TechSpiritSS** [comment]
Cool! add this project into project_doc.md file as well and make a sinlge Pull Request for both of them. Don't forgot to fetch the main branch first

**Comment by TechSpiritSS** [comment]
You haven't fetch your repo before making the Pull Request which is causing the merge conflicts

**Comment by ManasviGoyal** [comment]
> You haven't fetch your repo before making the Pull Request which is causing the merge conflicts

i created another PR. closing this one.

**Pull request closed without merging**
