### PR TITLE
Added Exploratory_Analysis_Ernon_Dataset

### PR DESCRIPTION
**Pull request by ManasviGoyal**

### CODE REVIEW

**Comment by aflah02** [comment]
Hey, could you add the Jupyter Notebook as well, EDAs in python scripts are difficult to read

**Comment by aflah02** [comment]
Also some reference to the original dataset used would be great as it is I can't spot it also do add a project description as well

**Comment by ManasviGoyal** [comment]
Yes sure

**Comment by ManasviGoyal** [comment]
i think i added in wrong folder. Let me create a new pr

**Comment by ron2111** [comment]
Ok then, shall I close this one @ManasviGoyal

**Pull request closed without merging**
