### PR TITLE
feat: Add github dp loader javascript project 

### PR DESCRIPTION
**Pull request by anubhavbagri**
Small project made using javascript which shows github dp on entering github username in the input field. Made with [Axios](https://axios-http.com/) which helps in calling the github API enabling us to fetch user data including the url of their dp which is then shown on the screen.
> Also added project description to `Project_doc.md`

Trying my hands on open source by creating a Pull Request for Hacktober Fest 2021.

### CODE REVIEW

**Comment by ron2111** [comment]
Fetch upstream and then update ur name under the contributors list, its making some conflicts

**Comment by anubhavbagri** [comment]
Done @ron2111

**Comment by ron2111** [comment]
Great

**Comment by anubhavbagri** [comment]
Hey @ron2111 
Make sure there are less PR's accepted per day , to know more check [this](https://github.com/ishangoyal13/fullstackDevelopment/issues/550#issuecomment-932233017)

**Pull request merged**
