### PR TITLE
Create Stone-paper-scissor-game.py

### PR DESCRIPTION
**Pull request by varsha080**
I have created the stone paper scissor game using python. Kindly review it and merge it. In case of any conflict, let me know.

### CODE REVIEW

**Comment by TechSpiritSS** [comment]
readme.md is missing

**Comment by varsha080** [comment]
Do I have to update it there too?

**Comment by TechSpiritSS** [comment]
you have to create separate readme file for your project

**Comment by varsha080** [comment]
Okayy I'll make and create a PR again

**Pull request closed without merging**
