### PR TITLE
Added Machine Learning Project -> Heart Disease Classification

### PR DESCRIPTION
**Pull request by Sravanthgithub**
Hi there, I am Sravanth. I have added my recently done project.
Please merge my pull request.

Thank you!!

### CODE REVIEW

**Comment by aflah02** [comment]
Hey 
Do add a project readme for others and your name in the list of contributors

**Comment by Sravanthgithub** [comment]
> Hey Do add a project readme for others and your name in the list of contributors

yeah Did now!!

**Comment by Sravanthgithub** [comment]
Hey I did now!!
Please merge my pull request.

**Comment by Sravanthgithub** [comment]
Hey can you please tell me why my PR is not accepted?
So that I will improve.

**Pull request closed without merging**
