### PR TITLE
added Enron Exploratory analysis

### PR DESCRIPTION
**Pull request by ManasviGoyal**
dataset. it is quite big so can not be uploaded here
https://www.kaggle.com/wcukierski/enron-email-dataset

### CODE REVIEW

**Comment by ManasviGoyal** [comment]
@ron2111 check

**Comment by aflah02** [comment]
LGTM @ron2111 
No need to add the dataset just linking it would be good enough as a comment or something
Please add a project readme as well for others and your name in the list of contributors

**Comment by ManasviGoyal** [comment]
Where is the list of contributors?

**Comment by aflah02** [comment]
In the project readme

**Comment by ManasviGoyal** [comment]
done @ron2111

**Pull request merged**
