### PR TITLE
Adding a Snake Game using Python

### PR DESCRIPTION
**Pull request by Akashsri3bi**

### CODE REVIEW

**Comment by aflah02** [comment]
Code and Description LGTM
Don't forget to add your name in the README list of contributors

**Comment by TechSpiritSS** [comment]
There is conflict with your Project_doc.md fetch that first before making another Pull Request

**Comment by Akashsri3bi** [comment]
@TechSpiritSS can you please state the conflict

**Comment by Akashsri3bi** [comment]
@ron2111 @TechSpiritSS I made the changes in Project.md I Hope it will be fine

**Comment by TechSpiritSS** [comment]
> @TechSpiritSS can you please state the conflict

You haven't fetch upstream which is causing a merge conflict with your project_doc.md file

**Comment by Akashsri3bi** [comment]
@TechSpiritSS Fetch UpStream done

**Comment by TechSpiritSS** [comment]
create a new Pull Request after Fetching this is still causing conflicts

**Comment by ron2111** [comment]
resolve conflicts and raise another PR

**Pull request closed without merging**
