### PR TITLE
Added Fibonacci series with a twist

### PR DESCRIPTION
**Pull request by KeeganC09**
Added Fibonacci Series with a twist which replaces all prime numbers and multiples of 5 with "0"

### CODE REVIEW

**Review by ron2111 — CHANGES_REQUESTED** [review]
update project_doc.md file with the description of your project or add another readme file in your project folder.

**Comment by KeeganC09** [comment]
yes sure sir. On it. Thank you

**Comment by KeeganC09** [comment]
Made the change as you requested. Added a readme file in my project folder

**Comment by ron2111** [comment]
Merging, Star the repo if you like it.

**Comment by KeeganC09** [comment]
Yes. Starred the repo. Thank you

**Pull request merged**
