### PR TITLE
Breast Cancer Prediction (ML Project)

### PR DESCRIPTION
**Pull request by prathimacode-hub**
I had added up my name as a contributor in README.md, project in "ML Projects" and short intro of project in Projects_doc.md

Thanks for this opportunity to contribute. I'm a participant of Hacktober Fest. Kindly add the required label for my PR to get my contribution counted. Thank you. 👍

### CODE REVIEW

**Comment by ron2111** [comment]
Could you please review some PRs ?
If you are interested, will give you the write access, but please check all the steps in every PR like

1. Updation on project_doc.md
2. Name in the contributors list
3. Project should be under the respective techstack folder only
4. Dont merge projects with more than 100 file changes

**Comment by prathimacode-hub** [comment]
> Could you please review some PRs ? If you are interested, will give you the write access, but please check all the steps in every PR like
> 
> 1. Updation on project_doc.md
> 2. Name in the contributors list
> 3. Project should be under the respective techstack folder only
> 4. Dont merge projects with more than 100 file changes

Thank you for this opportunity. Sure, I would like to review it. Can you provide me write access to do so? @ron2111

**Comment by ron2111** [comment]
Ok, accept the invite please & thanks for the help :)

**Comment by prathimacode-hub** [comment]
> Ok, accept the invite please & thanks for the help :)

Most welcome, I had accepted the invite. @ron2111

**Pull request merged**
