### PR TITLE
Redesigned the Navbar in the Existing Project

### PR DESCRIPTION
**Pull request by Arko707**

### CODE REVIEW

**Comment by ron2111** [comment]
Always describe the changes you made & add them in the project_doc

**Comment by Arko707** [comment]
Actually, it's not my project I have just contributed to an existing project. And the changes made by me are just a few Frontend Works.
And there is no project_doc given in this project so as it's not my project should I add a project_doc.

**Comment by TechSpiritSS** [comment]
If you can add the project_doc.md for that do give, it will be great

**Comment by Arko707** [comment]
Although it's not my project then also I have added the readme.md file.

**Comment by TechSpiritSS** [comment]
Yeah, I saw that but you should try to make on PR for the both, I'll count this PR only. Great Work!

**Comment by Arko707** [comment]
No Issues!

**Pull request merged**
