### PR TITLE
BresenhamCircle.cpp

### PR DESCRIPTION
**Pull request by ABHIGPT401**

### CODE REVIEW

**Review by ron2111 — CHANGES_REQUESTED** [review]
add the description of your project in project_doc.md and your name in the list of contributors.

**Comment by ABHIGPT401** [comment]
done sir

**Comment by TechSpiritSS** [comment]
First Fetch the updated file then do your addition into the file

**Comment by ABHIGPT401** [comment]
didnt get it sir, can you explain it more please

**Comment by TechSpiritSS** [comment]
I'm closing this Pull Request, create a new Pull Request and do not edit Readme file in that

**Pull request closed without merging**
