### PR TITLE
Random password generator using python

### PR DESCRIPTION
**Pull request by smil-thakur**
hey, using python I created a script that can generate random password, you can ask it to make password with certain amount of letters, numbers and symbol a cool way to generate new password and can implemented in various  validation projects.

### CODE REVIEW

**Review by ron2111 — CHANGES_REQUESTED** [review]
Update project_doc.md with your project's description& add your name in the list of contributors in README.md

**Comment by smil-thakur** [comment]
Hey I just did the changes you told it’s giving some conflicts in readme.md please verify thanks in adv

**Comment by ron2111** [comment]
fetch upstream and then raise the pr again

**Comment by TechSpiritSS** [comment]
Fetch upstream and do not edit readme file

**Pull request closed without merging**
