### PR TITLE
added: TextUtils Web-App (by casafurix)

### PR DESCRIPTION
**Pull request by casafurix**
An easy-to-use, user-friendly text-utils app to manipulate and use your text in the way you want. Also, has dark mode feature, can be toggled on/off.

### CODE REVIEW

**Comment by casafurix** [comment]
done!

**Comment by casafurix** [comment]
is it okay now?

**Comment by casafurix** [comment]
hello, i have made the changes, is it okay now?

**Comment by TechSpiritSS** [comment]
There is issue with your Project_doc.md please fetch that before making Pull Request. and there is no need to edit readme files now

**Comment by casafurix** [comment]
i think its working now, please check and verify...thanks in advance!

**Comment by TechSpiritSS** [comment]
Great Work

**Comment by casafurix** [comment]
thanks a lot :))

**Pull request merged**
