### PR TITLE
Added News App Project in Web projects Folder

### PR DESCRIPTION
**Pull request by Aniket-508**
Updated contributors in readme, project doc in web folder and brief description about project in News App folder.

### CODE REVIEW

**Comment by ron2111** [comment]
There are some merge conflicts, resolve them and you are good to go

**Comment by Aniket-508** [comment]
Resolved conflicts, pls merge!

**Comment by Aniket-508** [comment]
Pls merge fast!!! @ron2111

**Comment by Aniket-508** [comment]
@prathimacode-hub @aflah02 @ron2111 @TechSpiritSS pls merge this because it will go on conflicting with others pls pls

**Comment by TechSpiritSS** [comment]
Create a new Pull Request and do not edit the Readme file in that, we will manually update all those readme files now.

**Pull request closed without merging**
