### PR TITLE
Santhoshcharan 001 patch 1

### PR DESCRIPTION
**Pull request by santhoshcharan-001**
<h2>General CV With HTML and CSS</h2>
This is a General CV of a person. And utilized HTML, CSS to do this.

### CODE REVIEW

**Comment by santhoshcharan-001** [comment]
Done. Please check again.

**Review by ron2111 — CHANGES_REQUESTED** [review]
remove the spaces between the link and brackets

**Comment by ron2111** [comment]
and there are some conflicts again

**Comment by santhoshcharan-001** [comment]
Changes done. Go through it.

**Comment by ron2111** [comment]
resolve conflicts and raise another PR

**Pull request closed without merging**
