### PR TITLE
Adding Real Estate Price Prediction Project.

### PR DESCRIPTION
**Pull request by ayushi424**
**Adding Real Estate Price Prediction Project.**
- I have added a Machine Learning Project as Real Estate Price Prediction.
Also, updated project_doc.md of ML project folder & added my name in contributors list in the README.md.

I am a **Hacktoberfest 2021** Participant.

### CODE REVIEW

**Review by prathimacode-hub — APPROVED** [review]
Your PR has conflicts. Kindly check it. 👍@ayushi424

**Comment by ayushi424** [comment]
@prathimacode-hub ,
There are conflicts in project_doc.md file and I have Updated Project README.md file by removing my name from contributors.
Still the conflicts are shown.
Please guide how to resolve them.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
It generally occurs when changes are done at a time by number of contributors else the main repo is not even with forked repo. Check for these things if it's obliging you. @ayushi424

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
All perfect. Now check if you could add your name as contributor in README.md @ayushi424

**Comment by ayushi424** [comment]
> All perfect. Now check if you could add your name as contributor in README.md @ayushi424

Should I add my name in contributors list in Project README.md now ?? @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Yes @ayushi424

**Comment by ayushi424** [comment]
> Yes @ayushi424

Done. Please Check @prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Good choice of project. 👏👍@ayushi424

**Comment by ayushi424** [comment]
> PR approved. Good choice of project. 👏👍@ayushi424

Thankyou @prathimacode-hub. Happy to see you here :)

**Pull request merged**
