### PR TITLE
Added Virtual_Assistance using python

### PR DESCRIPTION
**Pull request by suddhasattwakhan**
Made an app which will give you virtual assistance using python

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly update the details in projects_doc.md in "ML Projects" and your name as a contributor in README.md  @suddhasattwakhan

**Comment by suddhasattwakhan** [comment]
@prathimacode-hub sir i have successfully updates the readme and update the mlproject readme too. Please merge my pull request

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Ready to merge. @suddhasattwakhan 

@ron2111, check it.

**Comment by ron2111** [comment]
resolve conflicts and raise another PR

**Pull request closed without merging**
