### PR TITLE
Simple portfolio website

### PR DESCRIPTION
**Pull request by A-jha383**
Simple Portfolio website template create using CSS ,HTML and JavaScript.

### CODE REVIEW

**Comment by aflah02** [comment]
@ron2111 should we keep zip files? I feel code files in a folder would be better

**Comment by A-jha383** [comment]
ok

**Comment by aflah02** [comment]
LGTM don't forget to add your name in the contributors list

**Comment by A-jha383** [comment]
conflict resolved

**Comment by A-jha383** [comment]
conflict resolved

**Pull request merged**
