### PR TITLE
data science modelling project

### PR DESCRIPTION
**Pull request by karry26**

### CODE REVIEW

**Review by ron2111 — COMMENTED** [review]
i think your submodule es empty..

**Comment by karry26** [comment]
i updated please check

**Comment by ron2111** [comment]
there are some conflicts, pls resolve them

**Comment by karry26** [comment]
done

**Comment by TechSpiritSS** [comment]
There are merge conflicts in your repo fetch upstream before making Pull Request

**Comment by karry26** [comment]
done

**Pull request merged**
